### ISSUE TITLE
Q1

### ISSUE THREAD

**Issue by Aaron-Kyle** [TerryPei/AGCDM#1]
Hello, how does the model output the proficiency of knowledge points for students?

**Comment by TerryPei** [comment]
We can directly get the skills distribution by computing Q tables and slip/guess, which output in the third layer. Figure in the Appendix shows a case. But note that we can't directly get skills from latent traits because in the neural network, we map the skills to latent traits with a embedding function, and it's hard to represent the reversed functions of embedding to get the inputs.

**Comment by TerryPei** [comment]
> Hello, how does the model output the proficiency of knowledge points for students?

We can get the skills distribution by computing Q tables and slip/guess, which output in the third layer. Figure3 in the Appendix shows a case. But note that we can't directly get skills from latent traits because in the neural network, we map the skills to latent traits with a embedding function, and it's hard to represent the reversed functions of embedding to get the inputs.
